version: "3.9"

services: 

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    # command: python manage.py runserver 0.0.0.0:8000
    # command: exec gunicorn core:wsgi:application -b 0.0.0.0:8000 --reload
    volumes:
      - .:/usr/src/app/
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0

  nginx:
    restart: always
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on: 
      - web
    ports: 
      - "8005:80"
    volumes:
      - ./backend/static/:/static
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    # environment:
      # - NGINX_ENTRYPOINT_QUIET_LOGS=1  # включает лог старта контейнера